name: Run SonarQube with Maven

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven cloud
      run:  mvn -B verify sonar:sonar -Dsonar.projectKey=EbenezerGyamfi_devops-training-java-reachability-playground  -Dsonar.organization=EbenezerGyamfi -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONARCUBEKEY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCUBEKEY }}



ebenezergyamfi